export const ACTIVITIES_LOADING = 'ACTIVITIES_LOADING';
export const ADD_ACTIVITIES = 'ADD_ACTIVITIES';
export const ACTIVITIES_FAILED = 'ACTIVITIES_FAILED';

export const ADD_REVIEWS = 'ADD_REVIEWS';
export const REVIEWS_FAILED = 'REVIEWS_FAILED';

export const PARTNERS_LOADING = 'PARTNERS_LOADING';
export const ADD_PARTNERS = 'ADD_PARTNERS';
export const PARTNERS_FAILED = 'PARTNERS_FAILED';